#!/bin/sh 
# 
# HangUp pppd 
# 
# usage: 
#      pppd_kill IP_address 
# 
# Add next string to /etc/sudoers: 
# 
# apache   ALL = NOPASSWD: /usr/abills/misc/pppd_kill 
# 
# For remote hangup 
# /etc/inetd.conf
# hangup    stream  tcp     nowait  root    /usr/abills/misc/ppp_kill ppp_kill server 
# /etc/services
# hangup	30000/tcp

if [ w$1 = wserver ] ; then
  read IP_ADDR
else if [ w$1 = w ] ; then
  echo "Linux pppd kill script"
  echo "pppd_kill [port]";
  exit;
else
  IP_ADDR=$1 
fi
fi

  INTERFACE=`ifconfig | awk -v RS='\n\n'  "/$IP_ADDR / {print \\$1}"` 
  PPP_PID=`cat /var/run/$INTERFACE.pid` 

  kill -1 $PPP_PID
