#!/usr/bin/perl
# Card System




foreach my $prefix (@INC) {
  my $realfilename = "$prefix/Abills/modules/$module{$index}/lng_$html->{language}.pl";
  if (-f $realfilename) {
    $lang_file =  $realfilename;
    require $lang_file;
    last;
   }
 }

if ($lang_file eq '')  {
  require "Abills/modules/Docs/lng_english.pl";
}


use Paysys;
my $Paysys = Paysys->new($db, $admin, \%conf);


my %PAY_SYSTEMS = (1 => "Webmoney");
my @status = ('ENABLE', 'DISABLE', 'USED');



#**********************************************************
#
#**********************************************************
sub paysys_payment {
	paysys_webmoney();
}

#**********************************************************
#
#**********************************************************
sub paysys_log {
 	

if ($FORM{info}) {
	$Paysys->info($FORM{info});

  my $table = $html->table( { width => '400',
                              rows => [ [ "ID",            $Paysys->{ID}       ],
                                        [ "$_LOGIN",       $Paysys->{LOGIN}    ],
                                        [ "$_DATE",        $Paysys->{DATETIME} ],
                                        [ "$_SUM",         $Paysys->{SUM}      ],
                                        [ "$_PAY_SYSTEM",  $PAY_SYSTEMS{$Paysys->{SYSTEM_ID}}        ],
                                        [ "$_TRANSACTION", $Paysys->{TRANSACTION_ID}  ],
                                        [ "IP",            $Paysys->{IP}       ],
                                        [ "$_INFO",        $Paysys->{INFO}     ]
                                       ]
                               } );

   print $table->show();
 }
elsif(defined($FORM{del}) && $FORM{is_js_confirmed}) {
  $Paysys->del($FORM{del});

  if (! $Paysys->{errno}) {
    $html->message('info', $_DELETE, "$_DELETED $FORM{del}");
   }
}

if ($Paysys->{errno}) {
  $html->message('err', $_ERROR, "[$Paysys->{errno}] $err_strs{$Paysys->{errno}}");
 }




my %info = ();
$info{PAY_SYSTEMS_SEL}=$html->form_select('PAYMENT_SYSTEM', 
                                          { 
 	                                          SELECTED  => $FORM{PAYMENT_SYSTEM},
 	                                          SEL_HASH  => \%PAY_SYSTEMS,
 	                                          NO_ID     => 'y'
 	                                        });


form_search({ SEARCH_FORM => $html->tpl_show(_include('paysys_search', 'Paysys'), { %info, %FORM }, { notprint => 1 })  
	            });




my $list = $Paysys->list( { %LIST_PARAMS } );	
my $table = $html->table( { width      => '100%',
                            caption    => "Paysys",
                            border     => 1,
                            title      => ['ID', "$_LOGIN", "$_DATE", "$_SUM", "$_PAY_SYSTEM", "$_TRANSACTION", "IP", '-', '-'],
                            cols_align => ['left', 'left', 'right', 'right', 'left', 'right', 'right', 'center:noprint', 'center:noprint'],
                            qs         => $pages_qs,
                            pages      => $Paysys->{TOTAL}
                           });

foreach my $line (@$list) {
 
  $table->addrow($line->[0],
   $html->button("$line->[1]", "index=15&UID=$line->[8]"), 
   "$line->[2]", 
   "$line->[3]", 
   "$PAY_SYSTEMS{$line->[4]}", 
   "$line->[5]",
   "$line->[6]",
   $html->button($_INFO, "index=$index&info=$line->[0]"),
   $html->button($_DEL, "index=$index&del=$line->[0]", { MESSAGE => "$_DEL $line->[0]?" })
   );
}
print $table->show();

$table = $html->table( { width      => '100%',
                         cols_align => ['right', 'right'],
                         rows       => [ [ "$_TOTAL:", "<b>$Paysys->{TOTAL}</b>" ] ]
                        } );
print $table->show();


}




#**********************************************************
#
#**********************************************************
sub paysys_webmoney () {


if ($FORM{LMI_PAYMENT_NO}) {

  my $payments = Finance->payments($db, $admin, \%conf);
	my $users = Users->new($db, $admin, \%conf); 
	my $user = $users->info($FORM{UID});
	
	if ($user->{errno}) {
		print $html->message('err', $_ERROR, "$_ERROR $user->{errno}");
	 }
	elsif ($user->{TOTAL} < 0) {
		print $html->message('err', $_ERROR, "$_NOT_EXIST");
	 }
	else {
    my $list = $Paysys->list({ TRANSACTION_ID => $FORM{'LMI_PAYMENT_NO'}, UID => $LIST_PARAMS{UID} });
    if ($Paysys->{TOTAL} > 0) {
	    print $html->message('info', $_INFO, "$_ADDED $_SUM: $list->[3] ID: $FORM{LMI_PAYMENT_NO}");
	   }
    else {
    	print $html->message('err', $_ERROR, "$_FAILED ID: $FORM{LMI_PAYMENT_NO}");
     }
	 }

  return 0;
 }
elsif ($FORM{FALSE}) {
	print $html->message('err', $_ERROR, "$_FAILED ID: $FORM{LMI_PAYMENT_NO}");
 }
  



my %info = ();
$info{LMI_PAYMENT_NO} = mk_unique_value(8, {  SYMBOLS => '0123456789' });
$info{TEST_MODE}="<font color='red'>$_TEST_MODE</font>" if ($conf{PAYSYS_LMI_MODE}); 


$conf{PAYSYS_LMI_RESULT_URL} = "http://$ENV{SERVER_NAME}$ENV{REQUEST_URI}" if (! $conf{PAYSYS_LMI_RESULT_URL});
$html->tpl_show(_include('paysys_webmoney_add', 'Paysys'), \%info);


}





sub wm_validate {
	
	
	eval { require Digest::MD5; };
 if (! $@) {
    Digest::MD5->import();
   }
 else {
    log_print('LOG_ERR', "Can't load 'Digest::MD5' check http://www.cpan.org");
  }

  my $md5 = new Digest::MD5;
  $md5->reset;

	$md5->add($FORM{LMI_PAYEE_PURSE}); 
	$md5->add($FORM{LMI_PAYMENT_AMOUNT});
  $md5->add($FORM{LMI_PAYMENT_NO});
  $md5->add($FORM{LMI_MODE}); 
  $md5->add($FORM{LMI_SYS_INVS_NO});
  $md5->add($FORM{LMI_SYS_TRANS_NO});
  $md5->add($FORM{LMI_SYS_TRANS_DATE});
  $md5->add($FORM{LMI_SECRET_KEY}); 
  $md5->add($FORM{LMI_PAYER_PURSE}); 
  $md5->add($FORM{LMI_PAYER_WM}); 

  my $digest = $md5->digest();	
  
  print bin2hex($digest);
}



#***********************************************************
# bin2hex()
#***********************************************************
sub bin2hex ($) {
 my $bin = shift;
 my $hex = '';
 
 for my $c (unpack("H*",$bin)){
   $hex .= $c;
 }

 return $hex;
}


1

