#!/usr/bin/perl
# Card System



my @status = ('ENABLE', 'DISABLE', 'USED');



#**********************************************************
#
#**********************************************************
sub paysys_webmoney () {


 wm_validate();

if ($FORM{TRUE}) {

  my $payments = Finance->payments($db, $admin, \%conf);
	my $users = Users->new($db, $admin, \%conf); 
	my $user = $users->info($FORM{UID});
	
	if ($user->{errno}) {
		print $html->message('err', $_ERROR, "$_ERROR $user->{errno}");
	 }
	elsif ($user->{TOTAL} < 0) {
		print $html->message('err', $_ERROR, "$_NOT_EXIST");
	 }
	else {
    my $er = ($FORM{'5.ER'}) ? $payments->exchange_info() : { ER_RATE => 1 } ;  
    $payments->add($user, {SUM          => '',
  	                       DESCRIBE     => '', 
  	                       METHOD       => 'Webmoney', 
  	                       EXT_ID       => $FORM{LMI_PAYMENT_NO}, 
  	                       ER           => $er->{ER_RATE} } );  

	
	  print $html->message('info', $_INFO, "$_ADDED $_SUM: $sum ID: $FORM{LMI_PAYMENT_NO}");
	 }

  return 0;
 }
elsif ($FORM{FALSE}) {
	print $html->message('err', $_ERROR, "$_FAILED ID: $FORM{LMI_PAYMENT_NO}");
 }
  
my %info = ();
$info{LMI_PAYMENT_NO} = mk_unique_value(8, {  SYMBOLS => '0123456789' });

$conf{PAYSYS_LMI_RESULT_URL} = "http://$ENV{SERVER_NAME}$ENV{REQUEST_URI}" if (! $conf{PAYSYS_LMI_RESULT_URL});
$html->tpl_show(_include('paysys_webmoney_add', 'Paysys'), \%info);


}





sub wm_validate {
	
	
	eval { require Digest::MD5; };
 if (! $@) {
    Digest::MD5->import();
   }
 else {
    log_print('LOG_ERR', "Can't load 'Digest::MD5' check http://www.cpan.org");
  }

  my $md5 = new Digest::MD5;
  $md5->reset;

	$md5->add($FORM{LMI_PAYEE_PURSE}); 
	$md5->add($FORM{LMI_PAYMENT_AMOUNT});
  $md5->add($FORM{LMI_PAYMENT_NO});
  $md5->add($FORM{LMI_MODE}); 
  $md5->add($FORM{LMI_SYS_INVS_NO});
  $md5->add($FORM{LMI_SYS_TRANS_NO});
  $md5->add($FORM{LMI_SYS_TRANS_DATE});
  $md5->add($FORM{LMI_SECRET_KEY}); 
  $md5->add($FORM{LMI_PAYER_PURSE}); 
  $md5->add($FORM{LMI_PAYER_WM}); 

  my $digest = $md5->digest();	
  
  print bin2hex($digest);
}



#***********************************************************
# bin2hex()
#***********************************************************
sub bin2hex ($) {
 my $bin = shift;
 my $hex = '';
 
 for my $c (unpack("H*",$bin)){
   $hex .= $c;
 }

 return $hex;
}


1

