Service activation notification


LOGIN: %LOGIN%
PRERIOD: %PERIOD%
%SUM%
UID: %UID%
TP_ID: %TP_ID%
$_TARIF_PLAN: %TP_NAME%
$_PRICE: %PRICE%
$_COMMENTS: %COMMENTS%
$_DEPOSIT: %DEPOSIT%
$_CREDIT: %CREDIT%
$_DATE: %ABON_DATE%
%BILL_ID%
%FEES_TYPE%
%CREATE_ACCOUNT%
E-mail: %EMAIL%
%ALERT%
DATETIME: %DATETIME%
NEXT_ABON_DATE: %NEXT_ABON_DATE%
%DISCOUNT%
%CREATE_DOCS%
%SEND_DOCS%
